### ISSUE TITLE
Don't set css styles directly in JS, use custom properties instead

### ISSUE THREAD

**Issue by joostf** [maanlamp/web-app-from-scratch-18-19#2]
https://github.com/maanlamp/web-app-from-scratch-18-19/blob/fe777c9faab1fdeb8759e46040e016fb50d9bc01/week1/public/js/app.js#L40

.style.setProperty

**Comment by maanlamp** [comment]
You're right! Done.

https://github.com/maanlamp/web-app-from-scratch-18-19/commit/680e90aec86888ff6f274dbc48089e02a0dad538#diff-ff2171ff13ac391b5c7cd6fc8b8675deR64
