### ISSUE TITLE
Use english names only

### ISSUE THREAD

**Issue by joostf** [maanlamp/web-app-from-scratch-18-19#3]
https://github.com/maanlamp/web-app-from-scratch-18-19/blob/fe777c9faab1fdeb8759e46040e016fb50d9bc01/week1/public/js/app.js#L50

**Comment by maanlamp** [comment]
Reserved this for refactoring, but was an easy fix.

Fixed in https://github.com/maanlamp/web-app-from-scratch-18-19/commit/a08ad043f6426c7809ed3d11f4867914361074b0#diff-ff2171ff13ac391b5c7cd6fc8b8675deR50
