### ISSUE TITLE
Use variables inside functions

### ISSUE THREAD

**Issue by Cavalon-io** [maanlamp/web-app-from-scratch-18-19#4]
Maybe you can contain these variables inside the functions that need acces to them. As const can't be reached in the functions above these vars could just be inside the callback of the event listener.

https://github.com/maanlamp/web-app-from-scratch-18-19/blob/0c03a74d23d4ec020e722d03ec23004520ab3787/week1/public/js/app.js#L28

**Comment by maanlamp** [comment]
Fair point :)

No longer using any global variables as of https://github.com/maanlamp/web-app-from-scratch-18-19/commit/373d954383c7bf9204dadbdd9e77bd2026b00cfd!
